/*
 * Copyright © 2009-2010 Larkwood Labs Software.
 *
 * Licensed under the Larkwood Labs Software Source Code License, Version 1.0.
 * You may not use this file except in compliance with this License.
 *
 * You may view the Source Code License at
 * http://www.larkwoodlabs.com/source-license
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the license.
 */

package com.larkwoodlabs.net.amt;

import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.UnknownHostException;
import java.nio.ByteBuffer;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.larkwoodlabs.common.exceptions.ParseException;
import com.larkwoodlabs.net.ip.IPPacket;
import com.larkwoodlabs.net.ip.igmp.IGMPMessage;
import com.larkwoodlabs.net.ip.igmp.IGMPv3QueryMessage;
import com.larkwoodlabs.net.ip.ipv4.IPv4Packet;
import com.larkwoodlabs.net.ip.ipv6.IPv6Packet;
import com.larkwoodlabs.net.ip.mld.MLDMessage;
import com.larkwoodlabs.net.ip.mld.MLDv2QueryMessage;
import com.larkwoodlabs.util.buffer.fields.ByteArrayField;
import com.larkwoodlabs.util.buffer.fields.ByteField;
import com.larkwoodlabs.util.buffer.fields.IntegerField;
import com.larkwoodlabs.util.logging.Logging;

/**
 * An AMT membership query message.
 * 
 * <pre>
 * 6.4. AMT Membership Query
 * 
 *    An AMT Membership Query packet is sent from the respondent back to
 *    the originator to solicit an AMT Membership Update while confirming
 *    the source of the original request.  It contains a relay Message
 *    Authentication Code (MAC) that is a cryptographic hash of a private
 *    secret, the originators address, and the request nonce.
 * 
 *    It is sent from the destination address received in the Request to
 *    the source address received in the Request which is the same address
 *    used in the Relay Advertisement.
 * 
 *    The UDP source port is the IANA reserved AMT port number and the UDP
 *    destination port is the source port received in the Request message.
 *    The UDP checksum MUST be valid in AMT control messages.
 * 
 *     0                   1                   2                   3
 *     0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *    |     Type=0x4  |     Flags     |         Response MAC          |
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *    |            Response MAC (continued)                           |
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *    |            Request Nonce                                      |
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *    |            IGMP Membership Query or MLD Listener Query        |
 *    |            (including IP Header)                              |
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *    |          Reserved             |     Gateway Port Number       |
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 *    |                                                               |
 *    +                                                               +
 *    |                                                               |
 *    +                       Gateway Address                         +
 *    |                                                               |
 *    +                                                               +
 *    |                                                               |
 *    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
 * 
 * 6.4.1. Type
 * 
 *    The type of the message.
 * 
 * 6.5.2. Flags
 * 
 *    An 8-bit flags field having the following format:
 *                     0 1 2 3 4 5 6 7
 *                    +-+-+-+-+-+-+-+-+
 *                    |   Reserved  |G|
 *                    +-+-+-+-+-+-+-+-+
 * 
 *    The "G" flag is set to 1 if Gateway Address and Port fields are present
 *    in the Query message (see below Section 6.5.6), and to zero if they are
 *    not.
 * 
 *    Other flags are currently unused and reserved: they are sent as zero
 *    and their value is ignored on receipt.
 * 
 * 6.5.3. Response MAC
 * 
 *    A 48-bit hash generated by the respondent and sent to the originator
 *    for inclusion in the AMT Membership Update.  The algorithm used for
 *    this is chosen by the respondent but an algorithm such as HMAC-MD5-48
 *    [RFC2104] SHOULD be used at a minimum.
 * 
 * 6.5.4. Request Nonce
 * 
 *    A 32-bit identifier used to distinguish this request echoed back to
 *    the originator.
 * 
 * 6.5.5. IGMP/MLD Query (including IP Header)
 * 
 *    The message contains either an IGMP Query or an MLD Multicast
 *    Listener Query.  The IGMP or MLD version sent should default to
 *    IGMPv3 or MLDv2 unless explicitly configured to use IGMPv2 or MLDv1.
 *    The IGMP/MLD Query includes a full IP Header.  The IP source address
 *    of the query would match the anycast address on the pseudo interface.
 *    The TTL of the outer header should be sufficient to reach the tunnel
 *    endpoint and not mimic the inner header TTL which is typically 1 for
 *    IGMP/MLD messages.
 *    
 * 6.5.6. Gateway information fields
 * 
 *    The "Gateway Port Number" and "Gateway Address" fields are present in
 *    the Query message if, and only if, the "G" flag is set in the Flags
 *    field.
 * 
 * 6.5.6.1. Gateway Port Number
 * 
 *    A 16-bit field containing a UDP port value.
 * 
 *    The Relay sets this field to the value of the UDP source port of the
 *    Request message that triggered the Query message.
 * 
 * 6.5.6.2. Gateway Address
 * 
 *    A 16-byte field containing the IP source address of the Request
 *    message that triggered this Query message.  The field contains an
 *    IPv4-compatible IPv6 address ([RFC4291], section 2.5.5.1) if the
 *    address is an IPv4 address (i.e. the IPv4 address prefixed with 96
 *    bits set to zero), or an IPv6 address.
 * 
 * </pre>
 * 
 * @author Gregory Bumgardner
 */
public final class AmtMembershipQueryMessage extends AmtEncapsulationMessage {

    /*-- Inner Classes ------------------------------------------------------*/
    
    public static class Parser extends AmtEncapsulationMessage.Parser {

        public Parser() {
            this(DEFAULT_QUERY_PACKET_PARSER);
        }

        public Parser(IPPacket.Parser ipParser) {
            super(ipParser);
        }

        @Override
        public AmtEncapsulationMessage constructMessage(ByteBuffer buffer) throws ParseException {
            return new AmtMembershipQueryMessage(buffer);
        }

        @Override
        public Object getKey() {
            return MESSAGE_TYPE;
        }

    }


    /*-- Static Variables ---------------------------------------------------*/
    

    public static final byte MESSAGE_TYPE = 0x4;
    public static final int BASE_MESSAGE_LENGTH = 12;

    /**
     * Singleton instance of parser for IP packets carrying IGMP or MLD query messages. 
     */
    public static final IPPacket.Parser DEFAULT_QUERY_PACKET_PARSER = getQueryPacketParser();

    public static final ByteField       GatewayAddressFlag = new ByteField(1);
    public static final ByteArrayField  ResponseMac = new ByteArrayField(2,6);
    public static final IntegerField    RequestNonce = new IntegerField(8);

    public static final IPv4Packet igmpGeneralQueryPacket;
    public static final IPv6Packet mldGeneralQueryPacket;

    static {
        IGMPv3QueryMessage igmpGeneralQuery = new IGMPv3QueryMessage((short) 0);
        igmpGeneralQueryPacket = IGMPv3QueryMessage.constructIPv4Packet(new byte[4], // Source address is zero for AMT
                                                                       IGMPv3QueryMessage.QUERY_DESTINATION_ADDRESS,
                                                                       igmpGeneralQuery);
        
        MLDv2QueryMessage mldGeneralQuery = new MLDv2QueryMessage();
        mldGeneralQueryPacket = MLDv2QueryMessage.constructIPv6Packet(new byte[16], // Source address is zero for AMT
                                                                      MLDv2QueryMessage.QUERY_DESTINATION_ADDRESS,
                                                                      mldGeneralQuery);
    }

    /*-- Static Functions ---------------------------------------------------*/
    
    /**
     * 
     * @return
     */
    public static IPPacket.Parser getQueryPacketParser() {
        IPPacket.Parser parser = new IPPacket.Parser();
        parser.add(IGMPMessage.getIPv4PacketParser());
        parser.add(MLDMessage.getIPv6PacketParser());
        return parser;
    }

    public static AmtMembershipQueryMessage.Parser constructParser() {
        AmtMembershipQueryMessage.Parser parser = new AmtMembershipQueryMessage.Parser();
        parser.setIPPacketParser(getQueryPacketParser());
        return parser;
    }

    /*-- Member Variables ---------------------------------------------------*/

    private InetSocketAddress gatewayAddress = null;

    /*-- Member Functions ---------------------------------------------------*/

    /**
     * 
     * @param responseMac
     * @param requestNonce
     * @param queryPacket
     */
    public AmtMembershipQueryMessage(final byte[] responseMac,
                                     final int requestNonce,
                                     final IPPacket queryPacket,
                                     final InetSocketAddress gatewayAddress) {
        super(BASE_MESSAGE_LENGTH, MESSAGE_TYPE, queryPacket);
        
        if (logger.isLoggable(Level.FINER)) {
            logger.finer(Logging.entering(ObjectId,
                                        "AmtMembershipQueryMessage.AmtMembershipQueryMessage",
                                        Logging.mac(responseMac),
                                        requestNonce,
                                        queryPacket));
        }
        
        GatewayAddressFlag.set(getBufferInternal(), gatewayAddress != null ? (byte)1 :(byte)0);
        setResponseMac(responseMac);
        setRequestNonce(requestNonce);
        setGatewayAddress(gatewayAddress);

        if (logger.isLoggable(Level.FINER)) {
            logState(logger);
        }
    }

    /**
     * 
     * @param segment
     * @throws ParseException
     */
    public AmtMembershipQueryMessage(final ByteBuffer segment) throws ParseException {
        super(segment, BASE_MESSAGE_LENGTH);

        if (logger.isLoggable(Level.FINER)) {
            logger.finer(Logging.entering(ObjectId, "AmtMembershipQueryMessage.AmtMembershipQueryMessage", segment));
            logState(logger);
        }
    }

    @Override
    public void log(final Logger logger) {
        super.log(logger);
        logState(logger);
    }
    
    /**
     * Logs value of member variables declared or maintained by this class.
     * @param logger
     */
    private void logState(final Logger logger) {
        logger.info(ObjectId + " : response-MAC="+Logging.mac(getResponseMac()));
        logger.info(ObjectId + " : request-nonce="+getRequestNonce());
    }

    @Override
    public final void writeTo(final ByteBuffer buffer) {
        
        if (logger.isLoggable(Level.FINER)) {
            logger.finer(Logging.entering(ObjectId, "AmtMembershipQueryMessage.writeTo", buffer));
        }
        super.writeTo(buffer);
        if (this.unparsedPacket == null && this.gatewayAddress != null) {
            buffer.put((byte)0);
            buffer.put((byte)0);
            int port = this.gatewayAddress.getPort();
            buffer.put((byte)((port >> 8) & 0xFF));
            buffer.put((byte)(port & 0xFF));
            byte[] address = this.gatewayAddress.getAddress().getAddress();

            // Is the address an IPv4 address?
            if (address.length == 4) {
                // Write leading zeros for /96 IPv6 mapping
                for (int i = 0; i<12; i++) {
                    buffer.put((byte)0);
                }
            }

            // Writes 4 or 16 bytes
            buffer.put(address);
        }
    }

    @Override
    public Byte getType() {
        return MESSAGE_TYPE;
    }

    /**
     * 
     * @return
     */
    public boolean getGatewayAddressFlag() {
        return (GatewayAddressFlag.get(getBufferInternal()) & 0x01) == 0 ? false : true;
    }

    /**
     * 
     * @param hasGatewayAddress
     */
    protected void setGatewayAddressFlag(final boolean hasGatewayAddress) {
        
        if (logger.isLoggable(Level.FINER)) {
            logger.finer(Logging.entering(ObjectId, "AmtMembershipQueryMessage.setGatewayAddressFlag", hasGatewayAddress));
        }
        
        GatewayAddressFlag.set(getBufferInternal(),hasGatewayAddress ? (byte)1 : (byte)0);
    }

    /**
     * 
     * @return
     */
    public byte[] getResponseMac() {
        return ResponseMac.get(getBufferInternal());
    }

    /**
     * 
     * @param responseMac
     */
    public void setResponseMac(final byte[] responseMac) {
        
        if (logger.isLoggable(Level.FINER)) {
            logger.finer(Logging.entering(ObjectId, "AmtMembershipQueryMessage.setResponseMac", Logging.mac(responseMac)));
        }
        
        ResponseMac.set(getBufferInternal(),responseMac);
    }

    /**
     * 
     * @return
     */
    public int getRequestNonce() {
        return RequestNonce.get(getBufferInternal());
    }

    /**
     * 
     * @param requestNonce
     */
    public void setRequestNonce(final int requestNonce) {
        
        if (logger.isLoggable(Level.FINER)) {
            logger.finer(Logging.entering(ObjectId, "AmtMembershipQueryMessage.setRequestNonce", requestNonce));
        }
        
        RequestNonce.set(getBufferInternal(),requestNonce);
    }

    /**
     * 
     * @return
     */
    public InetSocketAddress getGatewayAddress() {
        if (this.unparsedPacket != null) {
            int index = this.packet.getTotalLength();
            short port = (short)((this.unparsedPacket.get(index++) << 8) | this.unparsedPacket.get(index++));
            byte[] address = new byte[16];
            for (int i=0; i<16; i++) {
                address[i] = this.unparsedPacket.get(index++);
            }
            try {
                this.gatewayAddress = new InetSocketAddress(InetAddress.getByAddress(address),port);
            }
            catch (UnknownHostException e) {
            }
        }
        return this.gatewayAddress;
    }

    /**
     * 
     * @param gatewayAddress
     */
    public void setGatewayAddress(final InetSocketAddress gatewayAddress) {
        this.gatewayAddress = gatewayAddress;
        setGatewayAddressFlag(gatewayAddress != null);
        if (this.unparsedPacket != null) {
            int index = this.packet.getTotalLength() + 2;
            int port = this.gatewayAddress.getPort();
            this.unparsedPacket.put(index++,(byte)((port >> 8) & 0xFF));
            this.unparsedPacket.put(index++,(byte)(port & 0xFF));
            byte[] address = this.gatewayAddress.getAddress().getAddress();
            if (address.length == 4) {
                for (int i=0; i<12; i++) {
                    this.unparsedPacket.put(index++,(byte)0);
                }
                for (int i=0; i< 4; i++) {
                    this.unparsedPacket.put(index++,address[i]);
                }
            }
            else {
                for (int i=0; i< 16; i++) {
                    this.unparsedPacket.put(index++,address[i]);
                }
            }
        }
    }
}
